[package]
name = "hello_macro_derive"
version = "0.1.0"
authors = ["Pick1a1username <20301273+Pick1a1username@users.noreply.github.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.14.4"
quote = "0.6.3"
